project_id = "mfvdqjtpcroqjxavctnr"

[functions.verify-payment]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.generate-ticket-qr]
verify_jwt = false

[functions.verify-ticket-qr]
verify_jwt = false
